### ISSUE TITLE
Add Contribution guidelines

### ISSUE THREAD

**Issue by ManoBharathi890** [bibhuti9/DSA-leetCode-JavaScript-Solution#4]
Hey Hi  Bibhuti9, you are doing great work this will be helpful for many job seekers.

Add Contribution guidelines:
Question you might get what should Add !
Answer to below question and make a contribution guidelines using this answers.
1.  Who should contribute ?
2.  Do you stick only with Javascript solution or will you accept other programming languages.
3.  What are topics that are really important to crack the interview
4. Suggest some of the resource and website that will help to ace the interviews (include both paid and free). etc..

**Comment by bibhuti9** [comment]
Thanks for your suggestion #1 [ManoBharathi890](https://github.com/ManoBharathi890) now I added all points
